### ISSUE TITLE
Make it installable in Asgard 2

### ISSUE THREAD

**Issue by imagina** [BocianCZ/slider-module#22]
Hey, thank you for the module. It's working great :D!

Can you change the composer.json to make it installable in Asgard 2 via composer require. (I installed it via git clone)

I think with "asgardcms/core-module": "^1.0",  should be enough in the composer.json because the module is working fine in both versions.

Regards

**Comment by imagina** [comment]
No, sorry. Ignore my last comment. A couple of changes more were necessary to make it work in 2.0.

**Comment by imagina** [comment]
I just commited in a Fork the changes needed to make it compatible with 2.0
https://github.com/imagina/slider-module/commit/63454885e40315f4aa17ee1ad8e5087c504bfd85

Regards

**Comment by becquerel** [comment]
excellent, thank you. I created a 2.0 branch and will be happy to merge your PR if you send one

**Comment by imagina** [comment]
I just sent the PR.
