### ISSUE TITLE
Asgard core module namespace

### ISSUE THREAD

**Issue by mikemand** [BocianCZ/slider-module#37]
Hello,

For v2 of Asgard, the core modules' namespaces are now `idavoll/*` instead of `asgardcms/*`.

For example, you are requiring `asgardcms/core-module` but it should be `idavoll/core-module`.

**Comment by becquerel** [comment]
@mikemand thank you, fixed on `2.0` branch, and I will make a new release

**Comment by mikemand** [comment]
No problem. 👍
