### ISSUE TITLE
Validation is not working

### ISSUE THREAD

**Issue by ikashifullah** [BocianCZ/slider-module#43]
Hi @becquerel,

 I would like to have validation for title, caption, etc. Could you please guide me what should I do?

**Comment by becquerel** [comment]
@kashifullahwebdeveloper you can see that there are several request classes in `Http/Requests` namespace. You can put your validations there, using the `rules()` method

I have validation rules turned off by design, because I need to be able to set only some fields, sometimes I have slides completely without any fields, but if you need to put them in, you can just follow official Laravel documentation
https://laravel.com/docs/5.4/validation#form-request-validation

**Comment by ikashifullah** [comment]
@becquerel, Thank you so much for quick reply.

I have done the same for validation but no error is showing on slide creation page, you can see my `rules()` here: https://github.com/kashifullahwebdeveloper/slider-module/blob/master/Http/Requests/CreateSlideRequest.php#L10

**Comment by becquerel** [comment]
I think you need to take a look at the translation rules instead. You can check out how the original Asgard modules deal with the problem, for example here
https://github.com/AsgardCms/Blog/blob/2.0/Http/Requests/CreatePostRequest.php
it uses the methods `translationRules` and `translationMessages` instead of `rules` and `messages`

**Comment by ikashifullah** [comment]
Yes, I have used translationRules and translationMessages method but no luck, you can see it here:
https://github.com/kashifullahwebdeveloper/slider-module/blob/master/Http/Requests/CreateSlideRequest.php#L14-L19

**Comment by becquerel** [comment]
and is the slide actually saved ? Or does system throw you back to the form, without saving to DB, but without displaying the error message ?

**Comment by ikashifullah** [comment]
If we remove rules from `rules` method then record is saved to DB, else system throw you back to the form without displaying the error message.

**Comment by becquerel** [comment]
ok, I think I got it. I don't have a way to test it right now, but it seems that core Asgard requests are in fact extending ` Modules\Core\Internationalisation\BaseFormRequest;`, while my requests are only extending `Illuminate\Foundation\Http\FormRequest`

This might not be the actual problem, but that's as much as I can do without actually running the code

**Comment by ikashifullah** [comment]
I have used `BaseFormRequest `class for validation, but still no luck, could you please pull my changes and try at your end, so that I can see what I am doing wrong!
https://github.com/kashifullahwebdeveloper/slider-module/blob/master/Http/Requests/CreateSlideRequest.php#L3-L5

**Comment by ikashifullah** [comment]
Hi @becquerel, I solved my validation issue as:

First of all, I extend my Request File from `Modules\Core\Internationalisation\BaseFormRequest`, and used the rules only in translatable methods, i.e. `translationRules()` and `translationMessages()`, also added translated text in lang file, `slider.php` and finally made some changes in form, you can see all those changes in my latest commit here: https://github.com/kashifullahwebdeveloper/slider-module/commit/aee2203f81af696b96d9616df6bc47f73713976f.

I would love to add the validation in your slider module if you allow me to do so.


Thank you for amazing slider.

**Comment by becquerel** [comment]
Hi @kashifullahwebdeveloper 

sorry, I did not have time to deal with my opensource stuff for few days now. I would be more than happy to merge your pull request, should you wrap up your code and send it my direction. One thing I am concerned about are too strict validations though, I have several instances where the only required input is a slide title. It this would be the only required field, we can get that out right away. What do you think ?

I have an idea about configurable slide validations, where everybody could create their own validation rules in the configuration, but that would be for the next iteration.

**Comment by becquerel** [comment]
discssed in corresponding PR, validation may not be something we really want, sometimes it is useful to show just a picture
