### ISSUE TITLE
Error when install

### ISSUE THREAD

**Issue by cotiga** [BocianCZ/slider-module#50]
Hi
I have this error
`bociancz/slider-module v2.2.0 requires idavoll/core-module ~2.0`

My AsgardCms composer.json
        "idavoll/core-module": "~3.0",

**Comment by becquerel** [comment]
Hi @COTIGA and than you for the bug report. Slider module is currently not compatible with Asagard 3.0, since I did not have time to go through last pull requests. I will try to make up some time in the upcoming days

**Comment by cotiga** [comment]
OK,
Thanks for your prompt response

**Comment by becquerel** [comment]
should be all good, sorry for delay
