### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by Fisiu** [BocianCZ/slider-module#53]
Since bootstrap 4 is available, maybe it's worth to consider update plugin to make it compatible with bootstrap 4? I already have initial working version, if you are interested I can send pull request.

**Comment by becquerel** [comment]
Please, yes. I would like to keep bootstrap3 in place as a default for now, but there can definitely be another set of templates ready for bootstrap4 and let the user decide which one to use

**Comment by Fisiu** [comment]
@becquerel Bootstrap 4 template done, see #54.

**Comment by becquerel** [comment]
this was implemented in v3.1.0
