### ISSUE TITLE
File does not exist at path /module.json 

### ISSUE THREAD

**Issue by cjaffar** [BocianCZ/slider-module#61]
When I use this module in asgardcms using :
php artisan asgard:download:module bociancz/slider-module,

I get an error - File does not exist at path /module.json 

when this module is deleted, my asgardcms project works fine.

**Comment by becquerel** [comment]
@cjaffar sorry for long delay on this one. Please see #71 , you should be able to install Slider module  by using php artisan asgard:download:module bociancz/slider, it should put the module in the correct directory.

New readme is updated with this information
