### ISSUE TITLE
Nestable CSS/JS  file was not found inside public/modules

### ISSUE THREAD

**Issue by mohamedali850** [BocianCZ/slider-module#66]
In admin slider edit blade file its mentioned to load CSS/JS files as follows,
{!! Module::asset('slider:css/nestable.css') !!}
{!! Module::asset('slider:js/jquery.nestable.js') !!}
but inside public/modules, there is no folder called "slider". Because of this slider delete is not working and edit is working partially. 
When I created slider folder and copied css and js files from Slider modules assets folder to public/modules/slider/js and css its working perfectly.
Kindly look into this issue.

**Comment by becquerel** [comment]
Hi @mohamedali850 , thank you for the bug report. This actually works as expected, but it is not documented properly. I will update the docs when I get a minute.

What is missing in the docs is one more step in the installation, where you need to run `php artisan module:publish Slider` command, which moves all frontend assets to modules/slider folder

**Comment by becquerel** [comment]
fixed in 3.2.2

**Comment by mohamedali850** [comment]
Great! Thanks for the update. It would be helpful to other like me if you update the same document in asgardcms.com

**Comment by becquerel** [comment]
@mohamedali850 I agree, unfortunately, I do not have control over what is on asgardcms.com, there is no way to edit the info there
